const ThumborJS = require('../');
const test      = require('blue-tape');

const localsvr  = require('./.inc/get_local_svr');
const seckey    = require('./.inc/get_seckey');

test('responses', function(t) {
    const key  = seckey();
    const url  = 'foo/bar/qux.png';

    const inst = new ThumborJS(localsvr(), key);

    // TODO: perform some requests, with URLs generated by our class,
    //       against a running local Thumbor instance and validate the
    //       responses

    t.end();
});